apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: netbox
spec:
  virtualhost:
    fqdn: netbox.sandbox.cedille.club
    tls:
      secretName: tls-delegation/sandbox-tls
  routes:
  - conditions:
    - prefix: /
    services:
    - name: netbox
      port: 80
    timeoutPolicy:
      idle: 600s
      response: 600s
