apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: docmost
spec:
  virtualhost:
    fqdn: wiki.sandbox.etsmtl.club
    tls:
      secretName: tls-delegation/sandbox-tls
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: docmost
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s
