apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dify-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    audiences:
      - vault
    role: secret-reader
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dify-vault-db
spec:
  vaultAuthRef: dify-auth
  type: kv-v1
  mount: kv
  path: data/dify/default/dify-vault-db
  destination:
    name: dify-vault-db
    create: true
    type: kubernetes.io/basic-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dify-vault-redis
spec:
  vaultAuthRef: dify-auth
  type: kv-v1
  mount: kv
  path: data/dify/default/dify-vault-redis
  destination:
    name: dify-vault-redis
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dify-vault-app
spec:
  vaultAuthRef: dify-auth
  type: kv-v1
  mount: kv
  path: data/dify/default/dify-vault-app
  destination:
    name: dify-vault-app
    create: true
