apiVersion: storage.k8s.io/v1
kind: StorageClass
Kind: PersistentVolume
metadata:
  name: local-path-wait
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

spec:
  capacity:
    storage: 10Gi
  accesssModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/sentry-data"
  storageClassName: manual
