apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbin
spec:
  virtualhost:
    fqdn: httpbin.sandbox.cedille.club
    tls:
      secretName: tls-delegation/sandbox-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: httpbin
          port: 80
      timeoutPolicy:
        idle: 600s
        response: 600s
