apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docmost
  annotations:
    kube-score/ignore: pod-networkpolicy, pod-probes, container-security-context-readonlyrootfilesystem, container-security-context-privileged, container-security-context-user-group-id, container-image-tag
spec:
  serviceName: docmost
  replicas: 2
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      containers:
        - env:
            - name: APP_URL
              value: https://wiki.sandbox.etsmtl.club
            - name: REDIS_URL
              value: redis://redis.docmost.svc.cluster.local:6379
          image: docmost/docmost:0.21.0
          name: docmost
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: docmost-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost-pv-claim
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: dockerhub-pull
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["/bin/sh", "-c"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
          args:
            - chown -R 10001:10001 /app/data/storage;
              chmod -R 770 /app/data/storage;
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost-pv-claim
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: docmost-pv-claim
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 15Gi
        storageClassName: cephfs
