# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/sentry-kubernetes/charts/sentry?ref=master # Exemple de source
  # Ou vos propres fichiers YAML locaux :
  # - deployment.yaml
  # - service.yaml

namespace: sentry