---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: penpot-data-assets
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /path/to/your/local/path/penpot-data-assets
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: penpot-data-exporter
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /path/to/your/local/path/penpot-data-exporter
