apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  destination:
    namespace: httpbin
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-sandbox
  project: k8s-cedille-sandbox
  source:
    path: apps/httpbin/prod
    repoURL: https://github.com/ClubCedille/k8s-cedille-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
