apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: outline
spec:
  virtualhost:
    fqdn: outline.sandbox.cedille.club
    tls:
      secretName: tls-delegation/sandbox-tls
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: outline
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s
