apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prod/cnpg.yaml
  - prod/pvc.yaml
  - prod/ingress.yaml
  - prod/vault.yaml
helmCharts:
  - name: dify
    repo: https://langgenius.github.io/dify-helm
    version: 3.12.1
    releaseName: dify
    namespace: dify
    valuesFile: helm/values.yaml
    additionalValuesFiles:
      - overrides.yaml
